### ISSUE TITLE
how do I connect to the board without a programmer?

### ISSUE THREAD

**Issue by wegunterjrFIrefly** [xorbit/wESP32-tester#1]
The wesp32 site says to connect the board to PoE and confirm DHCP.  Other than using my own networking tools how else can I connect?

**Comment by xorbit** [comment]
You can either check whether you see a new device pop up in your DHCP clients list on your network, or use the serial terminal (through a wESP32-Prog or other ESP32 programmer/serial converter) and check lan.ifconfig() to see if the device received an IP.
